### ISSUE TITLE
Community navigation link routes need to be updated

### ISSUE THREAD

**Issue by Sphiinx** [MaddoxDevelopment/RSPeer-Api#15] opened 2019-03-28 20:02 UTC
Community navigation link routes need to be updated. The "Bot Management" link goes to the old bot management panel "https://bot.rspeer.org/" when it should be "https://app.rspeer.org/#/"

**Comment by MaddoxDevelopment** [comment] 2019-03-30 17:36
Duplicate of the other redirecting url issues.

**Closed by MaddoxDevelopment** 2019-03-30 17:36 UTC
